### ISSUE TITLE
Sometimes users don't apply consistent language tags across all translatable columns

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#157]
If you have no `default_language`, but have label/hint with language (`label::French`) and media with no language (`media::image`), you'll get unexpected behavior. That is, your labels will not be in French, they will be in the default language.

This was discovered here: https://forum.opendatakit.org/t/adding-media-column-results-in-blank-screen/10237

**Comment by KeynesYouDigIt** [comment]
Ill take a crack at this one unless theres a better one. PR forthcoming!

**Comment by KeynesYouDigIt** [comment]
Sorry I am just getting back to this, anyone know where exactly default_language is set? I am roving around the Survey class in survey.py but cant seem to pick out how its calculated and how to set it to null for tests. Is in in excel or the underlying OS that our code looks for this?

**Comment by KeynesYouDigIt** [comment]
OK - I see a default lang column in the solution excel sheet, now I have to simulate that being empty in a test.

**Comment by KeynesYouDigIt** [comment]
Closing in I hope, sorry for the delays :/

**Comment by lognaturel** [comment]
If @KeynesYouDigIt or someone else wants to take another look at this, I think the first step should be to define what the warning text should be and enumerate all the cases that need to be covered by tests.

One case that's easy to forget is translations in choice lists. Choice list labels can also be translated so can cause this problem as well. See a test at https://github.com/XLSForm/pyxform/compare/master...lognaturel:pyxform-355 that should produce a warning because the survey sheet has labels in the language `English (en)` but the choices sheet only has labels in the default language.

**Comment by KeynesYouDigIt** [comment]
Finally crawling my butt back to this one, let me know if its not a priority anymore for some reason.

**Comment by KeynesYouDigIt** [comment]
The warning messages we had before were confusing, but was the idea right? Something like

> For question {q}, we detect an untranslated {hint, media, choice-list}. It might be a good idea to set the default language.

**Comment by lognaturel** [comment]
Shoot, I missed these messages, @KeynesYouDigIt. I don't think warning for every question addresses this issue. I've written more on [this forum post](https://forum.getodk.org/t/missing-default-language-warning/25732/6?u=ln)

> The ideal would be to identify all localizable columns in the form and all languages in the form and make sure that every localizable column exists in every language.

> I believe the localizable column types are label, hint, media::image, media::video, media::audio but it would be good to double-check that in the code.

> For example, if a form has columns label, hint, media::image, that's great, no problem. Similarly, if it has label::French (fr), hint::French (fr), media::image::French (fr), that's also great. pyxform takes care of making French (fr) the default language and everything works as expected. The problem is if a form has columns label::French (fr), hint::French (fr) and media::image. Now there are two languages in play: default and French (fr). However, French (fr) is missing the media::image column and the default language is missing the label and hint columns.

> The challenge is to come up with a warning that would help a user. It might be something like "Translations are incomplete: languages French (fr) and default are missing columns. See https://xlsform.org/ for help."

**Comment by KeynesYouDigIt** [comment]
That is much better than the idea I had :sweat_smile: Can do and will do

**Comment by lognaturel** [comment]
One thing I want to acknowledge: this issue was filed with title "If you have columns with language and columns without language, warn about setting a default language" which prescribes a very specific action. I renamed it in my head to "Sometimes users don't apply consistent language tags across all translatable columns" which captures what I think is the more general user-facing problem and the one I've been trying to address. I realized re-reading one of @lindsay-stevens' comments that this was not explicit at all. Apologies for that. I've renamed the issue now.
