### ISSUE TITLE
Excel workbook with macro enabled not supported

### ISSUE THREAD

**Issue by khalifeserge** [XLSForm/pyxform#252]
If an excel workbook with macro enable is used I get the an error that I included below. I used macros in my excel workbook for all kind of custom functions and other automation scripts that help write consistent forms. I have a macro that insert a repeat group with a regular group nested in it for exemple. And another that increment the version when I save. This is a feature request and not a bug but I am not sure how to tag it as such

> G:\....\Survey Instruments>xls2xform wtp.xlsm wtp.xml
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files\python37\Scripts\xls2xform.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\pyxform\xls2xform.py", line 137, in main_cli
    enketo=args.enketo_validate)
  File "c:\program files\python37\lib\site-packages\pyxform\xls2xform.py", line 19, in xls2xform_convert
    json_survey = xls2json.parse_file_to_json(xlsform_path, warnings=warnings)
  File "c:\program files\python37\lib\site-packages\pyxform\xls2json.py", line 1003, in parse_file_to_json
    workbook_dict = parse_file_to_workbook_dict(path, file_object)
  File "c:\program files\python37\lib\site-packages\pyxform\xls2json.py", line 986, in parse_file_to_workbook_dict
    raise PyXFormError("File was not recognized")
pyxform.errors.PyXFormError: File was not recognized

**Comment by ukanga** [comment]
Is it possible to share a simple Excel file with macros enabled? It will help in replicating the issue to better understand how it can be addressed.

**Comment by khalifeserge** [comment]
Attached are two identical files ones with macro enabled but not actual macro inside of it. I had to zip them because github does not allow uploading xlsm files
[Survey Instruments.zip](https://github.com/XLSForm/pyxform/files/2767831/Survey.Instruments.zip)

**Comment by ukanga** [comment]
@khalifeserge does the PR #254 address your issue?

Also, does us opening up `.xlsm` extension make systems that store and make these files available to other users vulnerable to viruses as well as aid in the spreading of viruses? Should we avoid processing these files in general because this increases the security risks to users since they can always save the file with `.xlsx` when they need to convert it to XForm?

@yanokwa any thoughts on my concerns above?

**Comment by yanokwa** [comment]
@ukanga asking the hard maintainer questions 😂

I bias towards allowing xlsm because it does make form design easier for folks. [xlrd's readme](https://github.com/python-excel/xlrd) says they safely ignore macros so I think as far as processing files we are fine. And if such a large library allows xlsm, we can probably do it to.

But systems like Ona that store those files and make them available for download might want to have some virus checking (e.g., like Google does with Gmail).
