### ISSUE TITLE
Support csv-external for defining an external instance not necessarily used for a select

### ISSUE THREAD

**Issue by ggalmazor** [XLSForm/pyxform#271]
https://github.com/opendatakit/xforms-spec/issues/88 introduces a new external itemsets in csv feature to the specs. This has been already implemented in JavaRosa with https://github.com/opendatakit/javarosa/pull/397 and it looks like we could implement this in PyXForm now too.

**Comment by lognaturel** [comment]
I'm pretty sure using secondary external instances as itemsets already works using `select_one_from_file`/`select_multiple_from_file`. However, the resulting XML needs some manual edits because of https://github.com/XLSForm/pyxform/issues/286. Does that sound right, @MartijnR?

Perhaps the "todo" here is to add type=`csv-external` by analogy to https://github.com/XLSForm/pyxform/issues/107

**Comment by MartijnR** [comment]
> However, the resulting XML needs some manual edits because of #286.

Yes indeed. 

> Perhaps the "todo" here is to add type=csv-external by analogy to #107

Yes, I agree.

**Comment by MartijnR** [comment]
Everybody still on board with adding `csv-external` (similar to the existing `xml-external`)?

**Comment by MartijnR** [comment]
Oops, I see there is a PR already but it appears to be abandoned. It could perhaps serve as a base for a new PR. https://github.com/XLSForm/pyxform/pull/298
