### ISSUE TITLE
Create or Update documentation in readme and others.

### ISSUE THREAD

**Issue by ukanga** [XLSForm/pyxform#273]
- [ ] Having a published https://readthedocs.org/ or equivalent documentation of code an library.

**Comment by geofire** [comment]
Bumping this as the project documentation is woefully out of date. The /docs folder doesn't appear to have been touched for 5 years (at time of writing). The documentation within it still references version 0.5, when pyxform is now at release 2.0.2. (!!!)

I've started toying with Sphinx 7.2.6 though its clear that this is going to be a much bigger body of work than one person alone can handle, as a significant chunk of the pyxform functionality is missing from the index.rst file that allows Sphinx to build the documentation from code.

I'm finding very much that the lack of documentation around pyxform is making it very hard to develop with. Web searches can only get one so far. I'll do what I can, though it will take a while without assistance from others.

**Comment by geofire** [comment]
Okay, found a way to streamline this.

I'm unsure if Sphinx had this functionality in 1.0.7, though Sphinx 7.2.8 includes the `sphinx-apidoc` function that can automatically generate reStructuredText files from code:

<pyxform root directory> `sphinx-apidoc -o docs/source .` (builds .rst files into docs/source)

Running it against the pyxform codebase automates the generation of these files, at least to enable manual customisation later if required.

As far as I can tell generating the `index.rst` file is still a manual process though updating the projects documentation as a whole is greatly sped up, providing the relevant code is commented correctly, by linking the generated .rst files in `index.rst`:

`Contents
========

.. toctree::
   :maxdepth: 2

   modules
   pyxform.entities
   pyxform.parsing
   pyxform
   pyxform.util
   pyxform.validators.enketo_validate
   pyxform.validators.odk_validate
   pyxform.validators.pyxform
   pyxform.validators`

Its then simply a case of running `sphinx-build` to create the documentation files.

**Comment by lognaturel** [comment]
Hi! Can you please share a bit about what you’re trying to accomplish? This could be a better high-level conversation for the ODK forum - https://forum.getodk.org/

ODK has been maintaining XLSForm/pyxform for several years now. It has never had a very explicit public API. We’re careful to make sure input forms result in the same Collect and Enketo behavior but other than that do not make strong guarantees around interface stability. That’s something we should document better.

**Comment by lognaturel** [comment]
Closing because we'll remove the sphinx docs in https://github.com/XLSForm/pyxform/pull/685/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR103

**Comment by geofire** [comment]
> Hi! Can you please share a bit about what you’re trying to do — contribute to pyxform, customize a fork, build around it, etc? This could be a better high-level conversation for the ODK forum - https://forum.getodk.org/

Hi!

Perhaps a bit abstract, though I have been swamped with a significant workload in building and managing a number of Survey123 applications, as we're upgrading our server infrastructure to support this application.

I'm using Survey123 Connect which has worked okay for a while, but is quickly becoming limiting in navigating and refactoring surveys in Excel, not to mention Git doesn't play well with viewing the contents of .xlsx documents (due to their Zip container).

It's more about using `pyxform` to assist me in managing the development and maintenance of these forms in code, which is much easier in my view, than in Excel when they reach a certain size.

Whilst it might not be the exact remit of `pyxform` to do this, it has certainly been very helpful in converting these forms from .xlsx files into JSON to make them much easier to work with. I have only just managed to create a basic script to convert code based forms back into .xlsx  documents, which works really well albeit is quite basic in functionality at this time.

Happy to contribute where I can, though a lack of documentation on `pyxform`'s API has made it difficult to understand and use, let alone improve.

**Comment by lognaturel** [comment]
Thanks for sharing your use case! I'd recommend you check out https://github.com/Sjlver/yxf which has similar aims.
