### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by ukanga** [XLSForm/pyxform#274]
- [x] use https://github.com/ambv/black #306
- link other code issues to this issue
- check code quality on PRs, should be improving not regressing.

**Comment by lindsay-stevens** [comment]
Since 2021 there are [github actions](https://github.com/XLSForm/pyxform/tree/master/.github/workflows) run for every PR. It has a `verify` step that runs linters: black, isort, pycodestyle, and flake8; and a `test` step that runs the test suite in the supported environment combos.

Not sure there's much more that'd be worth running on every PR. For example: coverage, mypy, vulture etc can be useful but at this stage I'd prefer to run those as part of a cleanup PR than forcing it on every contribution.
