### ISSUE TITLE
2 translated media labels outputs a 3rd (default) language

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#32]
![screen shot 2015-04-14 at 3 26 35 pm](https://cloud.githubusercontent.com/assets/627350/7147778/ab341fbe-e2ba-11e4-8178-3874ceb31a0a.png)

Form source here: https://docs.google.com/spreadsheets/d/1HlxpC4ORzor94WXONUqJXbrrlrsSQAEXdGsiAviM4lU/edit?usp=sharing

The default language has no valid audio src (because it doesn't exist in the XLSForm).

XForm itext output is:

``` xml
<itext>
    <translation default="true()" lang="default">
        .....
    </translation>
    <translation lang="Russian">
        ......      
    </translation>
    <translation lang="Kyrgyz">
       .......
    </translation>
</itext>
```

But expected itext output is:

``` xml
<itext>
    <translation lang="Russian">
        .....
    </translation>
    <translation lang="Kyrgyz">
       .......
    </translation>
</itext>


```

**Comment by lognaturel** [comment]
I hadn't thought through this issue and it has come back up as part of https://github.com/XLSForm/pyxform/issues/157 which @lindsay-stevens has been tackling. I wanted to write up a few notes to have a record of some thoughts I've had. I think we should document this behavior better (or at all).

The result of this change is that selects have different translation rules than form controls. It used to be that for any missing language/ui text combination used anywhere, `pyxform` filled in `-`. [The spec](http://getodk.github.io/xforms-spec/#languages) says:

> The content should be the same (same set of text ids) but with all strings translated to the new language.

This is enforced by Validate for form controls so that's why the `-` is filled in. Having the `-` makes it relatively easy to spot missing translations.

After this change, choice labels and any other media can be omitted for languages as long as one language has a translation. I believe both Collect and Enketo fall back to the topmost language in the `itext` block.

@MartijnR do you remember any context around this? The particular example you shared seems odd because the default language would get a Kyrgyz recording. It does seem useful in cases like when choices are place names that should be the same across languages. It could lead to hard to spot bugs where languages are accidentally missing.

**Comment by MartijnR** [comment]
> @MartijnR do you remember any context around this? The particular example you shared seems odd because the default language would get a Kyrgyz recording.

I don't remember and took a trip down memory lane into the annals of the formhub, enketo, odk and kobotoolbox and my email and unfortunately, it didn't reveal a source. 

I also cannot quite imagine why you'd not include a media source for every language.

**Comment by lognaturel** [comment]
Thanks for taking the trip! 🧳 Hopefully the warnings addressing #157 will make any unintentional missing translations easy to track down so the discrepancy won't matter too much.
