### ISSUE TITLE
Migration to Python 3?

### ISSUE THREAD

**Issue by jkpr** [XLSForm/pyxform#53]
Esteemed maintainers: 

Guido, benevolent dictator for life, has renewed the call to transition projects from Python 2 to Python 3 at PyCon2015 (see https://youtu.be/G-uKNd5TSBw?t=1m21s). What are the thoughts of the pyxform team for doing this? Is it completely out of the question?

**Comment by dorey** [comment]
Hi @jkpr. I don't see it as a priority. I can think of a couple other things that would be good to see first:

 - build out the [`tests_v1`](https://github.com/XLSForm/pyxform/tree/master/pyxform/tests_v1) directory so that all features and settings are paired with specific tests of their functionality
 - reduce the java dependency by catching ODK Validate errors ahead of time (i doubt we will ever fully cut validate out of it, but spawning the java process each time we create a survey is slow)
 - with everything well tested, we can rewrite the large parts of the library so that it's clean, maintainable code that doesn't scare people away. At this point, I think python3 would be very appropriate

That said, I don't know if it's a big undertaking and requires getting too deep into the code or not. Feel free to try it out and report back if it's not too complicated to switch.

**Comment by pld** [comment]
It's also worth noting that a number of python 2 projects (like kobocollect
I believe) require pyxform and would need to move to python 3 or have an
actively maintained version of pyxform.

**Comment by dorey** [comment]
We could still support 2.7. It'd require dropping support for 2.6 and below, but that shouldn't be a problem.
