### ISSUE TITLE
Prevent choice filter from creating additional languages in form

### ISSUE THREAD

**Issue by cafootitt** [XLSForm/pyxform#59]
See sample xlsform [here](https://docs.google.com/spreadsheets/d/1tbDewaL2CWDvx9vdlZB-3UmcyOPap8gWUjy-pUvDi2k/edit#gid=0).  This is modified xlsform that is able to send data into OpenMRS via the openmrs_code column in choices sheet.  The choice filter causes openmrs_code to show up as an extra language in webform view.

@ukanga

**Comment by nribeka** [comment]
@cafootitt I don't think this is because you're adding the ```choice_filter```. I think this is because you have ```label::openmrs_code``` in your ```choices``` sheet.

The parser I think, because seeing ```label``` in the header, think that column is one of the language options. It then created a new options using ```openmrs_code``` as the language.

I'm seeing this tag in the itext section: ```<translation lang="openmrs_code">```

**Comment by lindsay-stevens** [comment]
This is a usage problem, answered above. For more details on how to use XLSForms, see https://xlsform.org/en/
