### ISSUE TITLE
Warning about missing choice label when choice has an image label

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#679]
#### Software and hardware versions 
pyxform v2.0.0

#### Problem description
Warning about missing choice label when choice has an image label

#### Steps to reproduce the problem
1. Convert a form with a choice list that only has image labels (no text labels) such as [this one](https://docs.google.com/spreadsheets/d/14X7QMCBH8G9VZhoG6tvOUPw9fycbNWm1ipr6XijtgHk/edit#gid=0)
2. Notice the warnings:
```
On the choices sheet there is a option with no label. [list_name : images-only] 
On the choices sheet there is a option with no label. [list_name : images-only] 
```

#### Expected behavior
If choices in the list have images, there should be no warning. This may not be compatible with some of the new approach to warnings that we've taken so they may need to be reconsidered.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lindsay-stevens** [comment]
>If choices in the list have images, there should be no warning. 
@lognaturel The warning that this comes from, which is a check for a choice name and label value, has been in the code base since 2012. On the XLSForm.org and docs.getodk.org, the label column is described as being one of 3 mandatory choices columns. Are we saying now that the label is (conditionally?) optional? Are any media OK in place of a label - or just images?

> This may not be compatible with some of the new approach to warnings that we've taken so they may need to be reconsidered.
Sorry but what is this referring to?

**Comment by lognaturel** [comment]
Confirmed that this is old behavior. I thought it was related to changes to language warnings but it's not.
