### ISSUE TITLE
Is formhub/uuid still useful?

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#95]
Or can it be removed from the output (both XML nodes, and the bind)?

**Comment by ukanga** [comment]
This only makes sense in Ona(onadata), it is something we inject after we get the XML from pyxform as such this probably should be an issue for http://github.com/onaio/onadata.

When it was introduced in Formhub, the intention was to allow us to identify a form uniquely since the `form_id` aka `id_string` was only unique in one account. The behaviour still is that the user defines the `form_id`.
How would you suggest we approach the issue of uniquely identifying a form when you have multiple accounts and the only items you have is a form submission?

**Comment by MartijnR** [comment]
Thanks. I guess it would be nice to be able to turn it off but I was just wondering if it was still being used.

**Comment by ukanga** [comment]
We still use it, quite more heavily since we allow submissions at `ona.io/submission` where people have access to forms with the same `id_string` on different accounts. If it has to be turned off, that will need to happen on the Ona data report. Pyxform does not introduce it. Any specific reason why it is a bother?

**Comment by MartijnR** [comment]
Aha, totally misunderstood. I thought pyxform added it. I'm using Ona almost exclusively for Enketo development, so I see it all the time. Apologies!
