### ISSUE TITLE
Whitespace after ${} should not be trimmed

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#96]
In the attached form, I get input and use it in a label as output. The XML that pyxform  0.9.24 outputs trims the whitespace after the input, and that breaks my form.

That is, when I write `${in} test`, pyxform reads that as `${in}test` and so my XML looks like this:

Actual: `<label><output value=" /whitespace/in "/>test</label></input>`
Expected: `<label><output value=" /whitespace/in "/> test</label></input>`

[whitespace.xlsx](https://github.com/XLSForm/pyxform/files/627663/whitespace.xlsx)

**Comment by batkinson** [comment]
So, I just experienced this myself. It seems that labels that _**start**_ with the variable reference are trimmed. It turned out that we were seeing this intermittently in Spanish forms with question labels. The questions that incorrectly started without the ¿ were exhibiting this behavior, but ones with it did _**not**_. By adding the leading ¿ we were able to work around this defect.

**Comment by batkinson** [comment]
It turns out the form is generated properly in its raw format. Unfortunately, it is corrupted by minidom's pretty printer. An attempt is made to collapse the whitespace around text after-the-fact with regular expressions, but unfortunately, the context of which whitespace was intentional vs. incidental (from the pretty printing) is gone. One solution is to collapse whitespace to a single space rather than eliminating it altogether.

**Comment by ukanga** [comment]
Cool. Any chance you can add a test for this in `pyxform/tests_v1/`? The below code should do.

```python
+        self.assertPyxformXform(
+            name='whitespace',
+            md="""
+            | survey  |                 |          |      |
+            |         | type            | label    | name |
+            |         | text            | A1       | a1   |
+            |         | note            | ${a1} A1 | n1   |
+            """,
+            xml__contains=[
+                '<label><output value=" /whitespace/a1 "/> A1 </label>',
+            ])
```
